config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy]

  def index
    @tasks = Task.all.order(:deadline)
  end

  def new 
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: 'Task successfully created.'
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warsztaty inFakt 2023 - TO-DO list</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-11">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "New task", new_task_path, method: :get, class: "btn btn-primary" %>
            </div>

            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">No.</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Todo item</th>
                  <th scope="col">Description</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @tasks.each_with_index  do |task, i| %>
                  <tr>
                    <th scope="row"><%= i + 1 %> </th>
                    <td><%= task.deadline%></td>
                    <td><%= task.title %></td>
                    <td><%= task.description %></td>
                    <td>
                      <%= button_to "Delete task", task, method: :delete, class: "btn btn-danger" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>
            
            <% if @task.errors.any? %>
              <% @task.errors.full_messages.each do |message| %>
                <%= content_tag :div, class: "alert alert-danger", role: 'alert' do -%>
                  <%= message %>
                <% end -%>
              <% end %>
            <% end %>
              
            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "Tasks list", tasks_path, method: :get, class: "btn btn-primary" %>
            </div>

            <%= form_for(@task, url: tasks_path, html: { class: 'row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2' }) do |f| %>
              <div class="form-group">
                <label class="form-label">
                  <span>Title</span>
                  <%= f.text_field :title, class: "form-control" %>
                </label>
              </div>

              <div class="form-group">
                <label class="form-label">
                  <span>Description</span>
                  <%= f.text_area :description, class: "form-control" %>
                </label>
              </div>

              <div class="form-group">
                <label class="form-label">
                  <span>Deadline</span>
                  <%= f.date_field :deadline, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %> 
                </label>
              </div>

              <button type="submit" class="btn btn-success">Save</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>